name: Bug Report
description: Create a report to help us improve

labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Please check [list of known bugs](https://github.com/olanti-p/BNME/blob/main/doc/BNME/BUGS.md) and the [bug tracker](https://github.com/olanti-p/BNME/issues) before opening a new issue.
        

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: >
        A clear and concise description of what the bug is,
        and how do you expect it to be.
      placeholder: |
        (...) is not working as intended and instead does (...).
        it should have been (...), because (...).
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a new project
        2. Create a new mapgen
        3. Select 'Bucket' tool
        4. There's no way to pan camera anymore
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        **If applicable**, add screenshots to help explain your problem.

  - type: textarea
    id: versions-and-configuration
    attributes:
      label: Versions and configuration
      description: |
        - To generate:`Exit editor to game` > `Main menu (ESC)` > `Debug Menu` > `Info` > `Generate game report`
        - Please update your OS version with a more precise version.
      placeholder: |
        - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
        - Game Version: [from the main menu, e.g. bnme-v0.1.23]
        - Ingame language: [Arabic or Bulgarian or Chinese (Simplified) or Chinese (Traditional) or Dutch or Esperanto or French or German or Italian (Italy) or Japanese or Korean or Polish or Portuguese (Brazil) or Russian or Serbian or Spanish (Argentina) or Spanish (Spain) or Turkish]
        - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.

        If applicable, please add relevant file(s) here:
        - Configuration, debug log and ImGui state (you can just zip `config/` folder)
        - Save file used as base for the editor (zipped)
        - Custom mods (zipped), or download links for mods. 
        - Project JSON file and/or export JSON file

      placeholder: |
        - note: you can drag and drop files in this issue post!
